version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    #command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD} --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so #--loadmodule ./target/release/librejson.dylib
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD} #--loadmodule ./target/release/librejson.dylib
    volumes:
      - cache:/data
    restart: always

volumes:
  cache:
    driver: local
