version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - cache:/data
    networks:
      - inkbunny-app
    restart: always

  inkbunny-app:
    build:
      context: ../..
      dockerfile: cmd/server/Dockerfile
    ports:
      - "1323:1323"
    environment:
      - PORT=1323
      - API_HOST=${API_HOST:-localhost:1323}
      - SD_HOST=${SD_HOST:-localhost:7860}
      - REDIS_HOST=redis-stack
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - REDIS_USER=${REDIS_USER:-default}
    volumes:
      - sqlite-data:/app
    depends_on:
      - redis-stack
    networks:
      - inkbunny-app
    restart: on-failure:3

volumes:
  cache:
    driver: local
  sqlite-data:
    driver: local

networks:
  inkbunny-app:
    driver: bridge
